from turtle import *

# choose a color:
colors = ["red", "orange", "yellow", "green", "blue", "purple", "violet"]


bgcolor("black")
pensize(5)
speed(0)
delay(0)
ht()


def curve():
    for i in range(200):
        right(1)
        forward(1)


begin_fill()
curve()
speed(0)
delay(0)
ht()

for i in range(200):
    for j in range(len(colors)):
        color(colors[j])
        forward(i)
        curve()
        begin_fill()
        right(91)
    color(colors[i % 9])
    forward(i)
    left(91)
    curve()
    end_fill()
    right(91)
    forward(i)
    right(91)
    curve()
    left(91)
    forward(i)
    left(91)
    curve()
    right(91)
    forward(i)
    right(91)
    curve()
    left(91)
    forward(i)
    left(91)
    curve()
    right(91)
    forward(i)
    right(91)
    curve()
    left(91)
    forward(i)
    left(91)
    curve()
    right(91)
    forward(i)
    right(91)
    curve()
    left(91)
    forward(i)
    left(91)
    curve()
    right(91)
    forward(i)
    right(91)
    curve()
    left(91)
    forward(i)
    left(91)
    curve()
    right(91)
    forward(i)
    right(91)
    curve()
    left(91)
    forward(i)
    left(91)
    curve()
    right(91)
    forward(i)
    right(91)
    curve()
    left(91)
    forward(i)
    left(91)
    curve()
    right(91)
    forward(i)
    right(91)
    curve()
    left(91)
    forward(i)
    left(91)
    curve()
    right(91)
    forward(i)
    right(91)
    curve()
    left(91)
    forward(i)
    left(91)

for i in range(900):

    for k in range(len(colors)):
        curve()
        color(colors[k])
        forward(i)
        right(120)
        curve()
    for j in range(len(colors)):
        color(colors[j])
        forward(i)
        right(91)
    color(colors[i % len(colors)])
    forward(i)
    left(120)
